# action.yml
name: 'Get Spring Version in Go'
description: 'Get Spring version'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  boot-url:
    description: 'URL of Spring Boot metadata'
    required: false
    default: "https://api.spring.io/projects/spring-boot/releases"
  starter-url:
    description: 'URL of Starter metadata'
    required: false
    default: "https://start.spring.io"
  insecure:
    description: 'true/false, Allow insecure metadata server connections when using SSL'
    required: false
    default: "false"
  boot-version:
    description: 'Spring Boot version, e.g. `x.y.z`, use current version if leave blank'
    required: false
  dependencies:
    description: 'List of dependency identifiers to include in the generated project, can separate with commas'
    required: false
outputs:
  spring-boot:
    description: 'Spring Boot version'
  spring-cloud:
    description: 'Spring Cloud version'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/shihyuho/go-spring-version:1.0'
  args:
    - --boot-url=${{ inputs.boot-url }}
    - --starter-url=${{ inputs.starter-url }}
    - --boot-version=${{ inputs.boot-version }}
    - --dependency=${{ inputs.dependencies }}
    - --output=github
